use_frameworks!

target 'ZPlaceholderTextView_Example' do
  pod 'ZPlaceholderTextView', :path => '../'

  target 'ZPlaceholderTextView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
